export const AD_LIST_REQUEST = 'AD_LIST_REQUEST';
export const AD_LIST_SUCCESS = 'AD_LIST_SUCCESS';
export const AD_LIST_FAIL = 'AD_LIST_FAIL';

export const AD_DETAILS_REQUEST = 'AD_DETAILS_REQUEST';
export const AD_DETAILS_SUCCESS = 'AD_DETAILS_SUCCESS';
export const AD_DETAILS_FAIL = 'AD_DETAILS_FAIL';

export const CATEGORY_AD_LIST_REQUEST = 'CATEGORY_AD_LIST_REQUEST';
export const CATEGORY_AD_LIST_SUCCESS = 'CATEGORY_AD_LIST_SUCCESS';
export const CATEGORY_AD_LIST_FAIL = 'CATEGORY_AD_LIST_FAIL';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL';
